# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(272, 158)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.button_add_transaction = QtWidgets.QPushButton(Form)
        self.button_add_transaction.setObjectName("button_add_transaction")
        self.verticalLayout.addWidget(self.button_add_transaction)
        self.button_list_transactions = QtWidgets.QPushButton(Form)
        self.button_list_transactions.setObjectName("button_list_transactions")
        self.verticalLayout.addWidget(self.button_list_transactions)
        self.button_exit = QtWidgets.QPushButton(Form)
        self.button_exit.setObjectName("button_exit")
        self.verticalLayout.addWidget(self.button_exit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "Stock Tracker"))
        self.button_add_transaction.setText(_translate("Form", "Add a transaction"))
        self.button_list_transactions.setText(_translate("Form", "List all transactions"))
        self.button_exit.setText(_translate("Form", "Exit application"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
